services:
  user-server:
    build:
      context: ./server
      dockerfile: services/user-service/Dockerfile
    ports:
      - "8000:8000"
    container_name: user-service
    env_file:
      - ./server/.env
    
    environment:
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true
      - WATCHFILES_POLL_INTERVAL=0.5
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload