"""add shipping fields

Revision ID: 2f74e7fae96d
Revises: 6cb9608babed
Create Date: 2026-07-20 21:19:11.601297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f74e7fae96d'
down_revision: Union[str, Sequence[str], None] = '6cb9608babed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_address1', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_city', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_state', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_postal_code', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_country', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_phone', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_email', sa.String(), nullable=True))
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('orders', 'shipping_email')
    op.drop_column('orders', 'shipping_phone')
    op.drop_column('orders', 'shipping_country')
    op.drop_column('orders', 'shipping_postal_code')
    op.drop_column('orders', 'shipping_state')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_address1')
    op.drop_column('orders', 'shipping_name')
    # ### end Alembic commands ###
