"""update this model

Revision ID: c2d398e86ab0
Revises: fc7b41b8d8eb
Create Date: 2026-04-24 20:58:08.329890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d398e86ab0'
down_revision: Union[str, Sequence[str], None] = 'fc7b41b8d8eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_details', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_details')
    # ### end Alembic commands ###
