"""update user_id field

Revision ID: 7b20d8e4bde5
Revises: 9e58f8bad9f0
Create Date: 2026-05-22 10:54:54.938883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b20d8e4bde5'
down_revision: Union[str, Sequence[str], None] = '9e58f8bad9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.String(), nullable=False))
    op.alter_column('comments', 'comment_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_comments_user_email'), table_name='comments')
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.drop_column('comments', 'user_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.create_index(op.f('ix_comments_user_email'), 'comments', ['user_email'], unique=False)
    op.alter_column('comments', 'comment_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
